#spring.datasource.url=jdbc:sqlserver://186.28.243.188:63138;databaseName=EMP004_FACT;encrypt=false;trustServerCertificate=true;loginTimeout=30;
spring.datasource.url=jdbc:sqlserver://186.28.243.188:63138;databaseName=EMP004_FACT;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=MDS1610solPRO

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


bitrix.webhook.base-url=https://proelectricos.bitrix24.es/rest/1/ftul4x2nzsd57uv8/




app.excel.template-path=templates/TAB-XXXXX-26.xlsx
app.excel.export-path=C:/Bitrix24/Exportaciones/

# Google Drive Config
google.drive.credentials-path=credentials.json
google.drive.application-name=RestIntCE
google.drive.root-folder-id=1uEZu6TnfzYbgJqDMeXeor_zu7QeZfg9w

